#model
model_name: conformer
device: cuda:0
conformer_checkpoint: ./model_ckp/conformer/conformer_S.pt
lora_checkpoint: ./model_ckp/lora/lora_S.pt
alpha: 0.5

#data
train_path: ./data/data_train_test_example.fasta
test_path: ./data/data_train_test_example.fasta
predict_path: ./data/data_predict_example.fasta
type: ['S']

#train
patience_limit: 5
patience_key: auc
num_epoch: 10
batch: 64
window_size: 15
split: 0.1

#opt
lr: 5e-5
beta1: 0.9
beta2: 0.999
weight_decay: 1e-4

#log & save
val_interval: 500
threshold: 0.5
log_path: ./log/conformrer
log_name: conformer_S-example
save_path: ./model_ckp/conformer
save_name: conformer_S-example
predict_result_path: ./result/conformer


