#model
model_name: conformer
device: cuda:2
conformer_checkpoint: ./model_ckp/conformer/conformer_Y.pt
lora_checkpoint: ./model_ckp/lora/lora_Y.pt
alpha: 0.5

#data
train_path: ./data/merged_train_Y.fasta
test_path: ./data/merged_test_Y.fasta
predict_path: ./data/data_predict_example.fasta
type: ['Y']

#train
patience_limit: 5
patience_key: auc
num_epoch: 5
batch: 64
window_size: 15
split: 0.1

#opt
lr: 5e-5
beta1: 0.9
beta2: 0.999
weight_decay: 1e-4

#log & save
val_interval: 500
threshold: 0.5
log_path: ./log/conformrer
log_name: conformer_Y_new
save_path: ./model_ckp/conformer
save_name: conformer_Y_new
predict_result_path: ./result/conformer


